/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3up;

import java.io.File;
import java.nio.file.Paths;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class EntryTest {
    @Test
    public void testSomeLibraryMethod() {
        String bucketName = "chia-test-7923-9832";

        File file = Paths.get("README.md").toFile();
        Upload.defaultSettings().uploadFile(file, bucketName);

        AtomicInteger returnCodeCatch = new AtomicInteger(-1);
        Entry.main(
                new String[] {
                    "--" + Entry.BUCKET_FLAG,
                    "foo",
                    "--" + Entry.DRYRUN_FLAG,
                    "--" + Entry.DELETE_LOCAL_FLAG,
                    "README.md"
                },
                returnCodeCatch::set);

        Assertions.assertEquals(returnCodeCatch.get(), 0);
    }
}
