/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3up;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;

class EntryTest {
    @Test
    public void testSomeLibraryMethod() {
        String bucketName = "chia-test-7923-9832";

        System.out.println();
        File file = Paths.get("../README.md").toFile();
        System.out.println(Paths.get("").toAbsolutePath().toString());
        Upload.uploadFile(file, bucketName);

        Entry.main(new String[]{Entry.BUCKET_FLAG, "foo", Entry.DRYRUN_FLAG, "true", "../README.md"});
    }
}
